# Generated by Django 5.2.4 on 2025-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True),
        ),
    ]
