# Generated by Django 5.2.4 on 2025-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc_app', '0002_add_pincode_to_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
