# Generated by Django 5.2.4 on 2025-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc_app', '0003_alter_complaint_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
