# Generated by Django 5.2.4 on 2025-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwc_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
